score_job:
  cron: "1 * * * * Asia/Seoul"
  class: "ScoreJob"
  queue: default
sitizen_job:
  cron: "30 * * * * Asia/Seoul"
  class: "Citizen2017Job"
  queue: default
speeches_view_count_job:
  cron: "15 * * * * Asia/Seoul"
  class: "SpeechesViewCountJob"
  queue: default
summary_mailing_job:
  class: SummaryMailingJob
  cron: "15 5 * * 1 Asia/Seoul"
  queue: default

